In [3]:
import numpy as np
import tensorflow as tf

In [7]:
def linear_function():
    X = tf.placeholder(tf.float64)
    W = tf.constant(np.random.randn(4, 3))
    b = tf.constant(np.random.randn(4, 1))
    Y = tf.add(tf.matmul(W, X), b)
    sess = tf.Session()
    result = sess.run(Y, feed_dict={X:np.random.randn(3, 1)})
    sess.close()
    return result

print("Result: " + str(linear_function()))

Result: [[-0.13544452]
 [-2.44570986]
 [-1.16815418]
 [ 0.77881796]]


In [14]:
def sigmoid(z):
    sigmoid = tf.sigmoid(z)
    with tf.Session() as sess:
        result = sess.run(sigmoid)
    return result

print("Sigmoid: " + str(sigmoid(12.)))

Sigmoid: 0.999994


In [16]:
#Better to use placeholder for sigmoid
def sigmoid_pl(z):
    x = tf.placeholder(tf.float32)
    sigmoid = tf.sigmoid(x)
    with tf.Session() as sess:
        result = sess.run(sigmoid, feed_dict={x:z})
    return result

print("Sigmoid with placeholder: " + str(sigmoid_pl(12)))

Sigmoid with placeholder: 0.999994


In [17]:
#Cost function is also pre-defined which includes sigmoid activation
def cost(logits, labels):
    z = tf.placeholder(tf.float32)
    y = tf.placeholder(tf.float32)
    cost = tf.nn.sigmoid_cross_entropy_with_logits(logits=z, labels=y)
    session = tf.Session()
    cost = session.run(cost, feed_dict={z:logits, y:labels})
    session.close()
    return cost

logits = sigmoid(np.array([0.2, 0.4, 0.7, 0.9]))
print("Cost: " + str(cost(logits, np.array([0, 0, 1, 1]))))

Cost: [ 1.00538719  1.03664088  0.4138543   0.39956614]


In [22]:
def one_hot_matrix(labels, C):
    C = tf.constant(C)
    one_hot_matrix = tf.one_hot(labels, C, axis=0)
    with tf.Session() as sess:
        result = sess.run(one_hot_matrix)
    return result

labels = np.array([1,2,3,0,2,1])
one_hot = one_hot_matrix(labels, 4)
print("One_hot_matrix: " + str(one_hot))

One_hot_matrix: [[ 0.  0.  0.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.]]


In [26]:
#Creating a vector of ones
def ones(shape):
    ones_array = tf.ones(shape)
    with tf.Session() as sess:
        result = sess.run(ones_array)
    return result

print("ones_array: " + str(ones(5)))

ones_array: [ 1.  1.  1.  1.  1.]
